config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'

	get 'pages/index'
	get 'pages/help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: {maximum: 50}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def index
	end

	def help
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tests</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/help.html.erb
<h1>Help</h1>
<%= link_to "Home", root_path %>
<%= link_to "Index", pages_index_path %>

app/views/pages/home.html.erb
<h1>Hello</h1>
<%= link_to "Help", pages_help_path %>
<%= link_to "Index", pages_index_path %>

app/views/pages/index.html.erb
<h1>Index</h1>
<%= link_to "Home", root_path %>
<%= link_to "Help", pages_help_path %>